# Generated by Django 3.2 on 2021-05-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link A bove To Read Blog Post...', max_length=200),
        ),
    ]
