# Generated by Django 3.2 on 2021-06-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20210527_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='', max_length=200),
        ),
    ]
